In [26]:
data ="""arithmetic mean for population and sample :
Mean(average)
Population(N)
Sample (n)
central tendency : refers to the use to determine the center of the distribution of data.
1(mean),2(median),3(mode= most frequent element(used in categorical elements missing data ).
Mean when we use when we don’t have any outleyrs when we have outleyer we use median because that time median give best result.
measure of dispersion{spread}:
variance.{when ever when the spared is high when the element is present in central region is high }
Population variance
sample variance
standard deviation.{standard deviation is should be high always by which data is highly distributed}
percentile and quartiles:
Percentile : a percentile is an a value below which a certain percentage of observation is lie.
five number summary:
Minimum ,first quartile(q1),median ,third quartile(q3),maximum.
Removing the outlawyers:
Lower fence :q1 – 1.5(IQR)
Upper fence : q3 – 1.5(IQR)
Interquartile range (IQR) = q3-q1
Q3(75%),,,Q1(25%)
After the third standard deviation the data we its called most of the time outlayers.
Advance statistic
Distribution:
Gaussian /normal distribution: when the data is equally distributed both the sides, they show bell curve.
Empirical rule :68(in first std)—92(in second std)—99.7(in third std)
Probability
addition rule (probability “or”)
mitual exectsive event: two events are mitual execlusive if it can not occur at the same time.
Ex: rolling dice {only one result we get }
non-mitual ececlusive : multiple event occur at the same time :
Ex: deck of cards :
Multiplication rule :
indipendent event :{when ever we role a dice the event geeting any result it is independent.
dependent event : {marble choosing game }
Permutation and combination :
 p-value :
hypothesis testing :
Null hypothesis : coin is fair :
Alternate hypothesis : the coin Is unfair:
Experiments :
Reject and aspect the null hypothesis:
Type one and type two error:
Type I error (false positive): the test result says you have coronavirus, but you actually don’t.
Type II error (false negative): the test result says you don’t have coronavirus, but you actually do.
One tailed and two tailed test :{when ever we find the value of normal graph in one side it is one tailed nither it is two tailed :
confident interval :
point estimate : the value of any ststistic that estimates the value of a parameter :
 Z-TEST : when we have a population standard deviation we use this :
 T-TEST: if you don’t have population standard deveatyion we use this :
Bank open at hypothesis quations ?
chai square test : it is a not parametric test that is performed on (nominal and ordinal )data.
Why are any specific test is done ? (imp quqtion)
Hypothesis reallife quations with preticle :
 covariance :
np.random :"""

In [37]:
##first asine indexing for each word 

In [43]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [45]:
tokenizer = Tokenizer()

In [47]:
tokenizer.fit_on_texts([data])

In [125]:
len(tokenizer.word_index)

220

In [51]:
## we go sentense by sentenses :


In [55]:
for sentence in data.split('\n'):
    print(sentence)

arithmetic mean for population and sample :
Mean(average)
Population(N)
Sample (n)
central tendency : refers to the use to determine the center of the distribution of data.
1(mean),2(median),3(mode= most frequent element(used in categorical elements missing data ).
Mean when we use when we don’t have any outleyrs when we have outleyer we use median because that time median give best result.
measure of dispersion{spread}:
variance.{when ever when the spared is high when the element is present in central region is high }
Population variance
sample variance
standard deviation.{standard deviation is should be high always by which data is highly distributed}
percentile and quartiles:
Percentile : a percentile is an a value below which a certain percentage of observation is lie.
five number summary:
Minimum ,first quartile(q1),median ,third quartile(q3),maximum.
Removing the outlawyers:
Lower fence :q1 – 1.5(IQR)
Upper fence : q3 – 1.5(IQR)
Interquartile range (IQR) = q3-q1
Q3(75%),,,Q1(25%)

In [57]:
# we here use tokinizer to goinig throw word bu word 

In [78]:
input_sequences = []

for sentence in data.split('\n'):
    tokenized_sample=(tokenizer.texts_to_sequences([sentence])[0])

    for i in range(1,len(tokenized_sample)):
        input_sequences.append(tokenized_sample[:i+1])

In [80]:
input_sequences

[[78, 22],
 [78, 22, 79],
 [78, 22, 79, 13],
 [78, 22, 79, 13, 7],
 [78, 22, 79, 13, 7, 33],
 [22, 80],
 [13, 48],
 [33, 48],
 [49, 81],
 [49, 81, 82],
 [49, 81, 82, 50],
 [49, 81, 82, 50, 1],
 [49, 81, 82, 50, 1, 14],
 [49, 81, 82, 50, 1, 14, 50],
 [49, 81, 82, 50, 1, 14, 50, 83],
 [49, 81, 82, 50, 1, 14, 50, 83, 1],
 [49, 81, 82, 50, 1, 14, 50, 83, 1, 84],
 [49, 81, 82, 50, 1, 14, 50, 83, 1, 84, 5],
 [49, 81, 82, 50, 1, 14, 50, 83, 1, 84, 5, 1],
 [49, 81, 82, 50, 1, 14, 50, 83, 1, 84, 5, 1, 34],
 [49, 81, 82, 50, 1, 14, 50, 83, 1, 84, 5, 1, 34, 5],
 [49, 81, 82, 50, 1, 14, 50, 83, 1, 84, 5, 1, 34, 5, 9],
 [35, 22],
 [35, 22, 85],
 [35, 22, 85, 23],
 [35, 22, 85, 23, 86],
 [35, 22, 85, 23, 86, 87],
 [35, 22, 85, 23, 86, 87, 51],
 [35, 22, 85, 23, 86, 87, 51, 88],
 [35, 22, 85, 23, 86, 87, 51, 88, 52],
 [35, 22, 85, 23, 86, 87, 51, 88, 52, 89],
 [35, 22, 85, 23, 86, 87, 51, 88, 52, 89, 10],
 [35, 22, 85, 23, 86, 87, 51, 88, 52, 89, 10, 90],
 [35, 22, 85, 23, 86, 87, 51, 88, 52, 89, 10,

In [85]:
## we use zero padding to equalize the list shape 

In [103]:
max_len =max([len(x) for x in input_sequences])# len of max string

In [155]:
max_len

27

In [109]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences,maxlen = max_len,padding='pre')

In [111]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  78,  22],
       [  0,   0,   0, ...,  78,  22,  79],
       [  0,   0,   0, ...,  22,  79,  13],
       ...,
       [  0,   0,   0, ..., 215,  77, 216],
       [  0,   0,   0, ...,  77, 216, 217],
       [  0,   0,   0, ...,   0, 219, 220]])

In [115]:
x = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [143]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [119]:
y

array([ 22,  79,  13,   7,  33,  80,  48,  48,  81,  82,  50,   1,  14,
        50,  83,   1,  84,   5,   1,  34,   5,   9,  22,  85,  23,  86,
        87,  51,  88,  52,  89,  10,  90,  91,  92,   9,   4,   3,  14,
         4,   3,  24,  11,  25,  93,   4,   3,  11,  94,   3,  14,  23,
        95,  36,  26,  23,  96,  97,  15,   5,  99, 100,   4,  38,   4,
         1, 101,   2,  39,   4,   1,  52,   2, 102,  10,  49, 103,   2,
        39,  37,  37,  27,  16,  27,   2, 104, 105,  39, 106, 107,  53,
         9,   2, 108,  54,   7, 109,   8,  40,   2, 110,   8,  17, 111,
        53,   8, 112, 113,   5, 114,   2, 115, 117, 118,  55,  56,  28,
        23,  41,  56,  29, 120,   1, 122,  57,  28,  58,  35,  59,  42,
        57,  29,  58,  35,  59,  42, 126,  42,  29,  28, 127,  28, 128,
         1,  41,  16,  27,   1,   9,   3, 130, 131,  51,   5,   1,  26,
       132, 134,  60,  34,   4,   1,   9,   2, 136,  54, 137,   1, 138,
       139, 140, 141, 142,  43, 144,  10,  55,  44, 145,  10, 14

In [121]:
## it is a multi class classification task 

In [123]:
# then we do one how encoding 

In [135]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y,num_classes=221)#always geeting one no higher on num_class 

In [139]:
y.shape

(394, 221)

In [145]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [147]:
## now we create a artitacture 

In [200]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [210]:
model = Sequential()

model.add(Embedding(input_dim=221,output_dim=100,input_length=27))
model.add(LSTM(150))
model.add(Dense(221,activation='softmax'))



In [212]:
model.build(input_shape= (None ,27))

In [214]:
model.compile(loss='categorical_crossentropy',optimizer ='adam',metrics = ['accuracy'])

In [216]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)              │ (None, 27, 100)             │          22,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_6 (LSTM)                        │ (None, 150)                 │         150,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 221)                 │          33,371 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 206,071 (804.96 KB)

 Trainable params: 206,071 (804.96 KB)

 Non-trainable params: 0 (0.00 B)

In [223]:
## now we train or model 

In [314]:
model.fit(x,y,epochs = 100,validation_data=(x,y))

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - accuracy: 0.9731 - loss: 0.1328 - val_accuracy: 0.9797 - val_loss: 0.1192
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9832 - loss: 0.1179 - val_accuracy: 0.9797 - val_loss: 0.1163
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9825 - loss: 0.1124 - val_accuracy: 0.9797 - val_loss: 0.1136
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 0.9778 - loss: 0.1132 - val_accuracy: 0.9797 - val_loss: 0.1113
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9814 - loss: 0.1139 - val_accuracy: 0.9797 - val_loss: 0.1091
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9802 - loss: 0.1056 - val_accuracy: 0.9797 - val_loss: 0.1066
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9842 - loss: 0.1013 - val_accuracy: 0.9797 - val_loss: 0.1056
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9780 - loss: 0.1028 - val_accuracy: 0.

In [294]:
tokenizer.word_index

{'the': 1,
 'is': 2,
 'we': 3,
 'when': 4,
 'of': 5,
 'test': 6,
 'and': 7,
 'a': 8,
 'data': 9,
 'in': 10,
 'have': 11,
 'hypothesis': 12,
 'population': 13,
 'use': 14,
 'result': 15,
 'standard': 16,
 'value': 17,
 'event': 18,
 'it': 19,
 'one': 20,
 'you': 21,
 'mean': 22,
 'median': 23,
 'don’t': 24,
 'any': 25,
 'time': 26,
 'deviation': 27,
 'q1': 28,
 'q3': 29,
 'two': 30,
 'type': 31,
 'tailed': 32,
 'sample': 33,
 'distribution': 34,
 '1': 35,
 'that': 36,
 'variance': 37,
 'ever': 38,
 'high': 39,
 'percentile': 40,
 'third': 41,
 'iqr': 42,
 'rule': 43,
 'std': 44,
 'mitual': 45,
 'at': 46,
 'error': 47,
 'n': 48,
 'central': 49,
 'to': 50,
 'most': 51,
 'element': 52,
 'which': 53,
 'distributed': 54,
 'first': 55,
 'quartile': 56,
 'fence': 57,
 '–': 58,
 '5': 59,
 'normal': 60,
 'probability': 61,
 'are': 62,
 'if': 63,
 'not': 64,
 'occur': 65,
 'same': 66,
 'ex': 67,
 'dice': 68,
 'null': 69,
 'coin': 70,
 'false': 71,
 'says': 72,
 'coronavirus': 73,
 'but': 74,
 'ac

In [320]:
import numpy as np 
import time 
text = "central tendency"

for i in range(27):
    # tokenize 
    token_text = tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text =pad_sequences([token_text],maxlen=56,padding='pre')
    #prediction
    pos =np.argmax(model.predict(padded_token_text))
    
    for word,index in tokenizer.word_index.items():
        if index == pos:
            text = text+" " +word
            print(text)
            time.sleep(0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
central tendency refers
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
central tendency refers to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
central tendency refers to the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
central tendency refers to the use
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
central tendency refers to the use to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
central tendency refers to the use to determine
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
central tendency refers to the use to determine the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
central tendency refers to the use to determine the center
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
central tendency refers to the use to determine the center of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
central tendency refers to the use to determine the center of the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
central tendency refers to the use to determine the center of the center
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
central tendency refers to th